using static MudBlazor.Phosphor.NumberValue;
using static MudBlazor.Phosphor.NumberVariant;

namespace MudBlazor.Phosphor;

public class SuperNumberIcon : SuperIcon
{
    [Parameter]
    public NumberVariant Variant { get; set; } = Normal;
    
    [Parameter]
    public NumberValue Value { get; set; } = Zero;
    
    public override string GetIcon()
    {
        return (Weight, Variant, Value) switch
        {
            // Regular
            (Regular, Normal, Zero) => PhosphorRegular.NumberZero,
            (Regular, Normal, One) => PhosphorRegular.NumberOne,
            (Regular, Normal, Two) => PhosphorRegular.NumberTwo,
            (Regular, Normal, Three) => PhosphorRegular.NumberThree,
            (Regular, Normal, Four) => PhosphorRegular.NumberFour,
            (Regular, Normal, Five) => PhosphorRegular.NumberFive,
            (Regular, Normal, Six) => PhosphorRegular.NumberSix,
            (Regular, Normal, Seven) => PhosphorRegular.NumberSeven,
            (Regular, Normal, Eight) => PhosphorRegular.NumberEight,
            (Regular, Normal, Nine) => PhosphorRegular.NumberNine,
            (Regular, Circle, Zero) => PhosphorRegular.NumberCircleZero,
            (Regular, Circle, One) => PhosphorRegular.NumberCircleOne,
            (Regular, Circle, Two) => PhosphorRegular.NumberCircleTwo,
            (Regular, Circle, Three) => PhosphorRegular.NumberCircleThree,
            (Regular, Circle, Four) => PhosphorRegular.NumberCircleFour,
            (Regular, Circle, Five) => PhosphorRegular.NumberCircleFive,
            (Regular, Circle, Six) => PhosphorRegular.NumberCircleSix,
            (Regular, Circle, Seven) => PhosphorRegular.NumberCircleSeven,
            (Regular, Circle, Eight) => PhosphorRegular.NumberCircleEight,
            (Regular, Circle, Nine) => PhosphorRegular.NumberCircleNine,
            (Regular, Square, Zero) => PhosphorRegular.NumberSquareZero,
            (Regular, Square, One) => PhosphorRegular.NumberSquareOne,
            (Regular, Square, Two) => PhosphorRegular.NumberSquareTwo,
            (Regular, Square, Three) => PhosphorRegular.NumberSquareThree,
            (Regular, Square, Four) => PhosphorRegular.NumberSquareFour,
            (Regular, Square, Five) => PhosphorRegular.NumberSquareFive,
            (Regular, Square, Six) => PhosphorRegular.NumberSquareSix,
            (Regular, Square, Seven) => PhosphorRegular.NumberSquareSeven,
            (Regular, Square, Eight) => PhosphorRegular.NumberSquareEight,
            (Regular, Square, Nine) => PhosphorRegular.NumberSquareNine,
            // Thin
            (Thin, Normal, Zero) => PhosphorThin.NumberZero,
            (Thin, Normal, One) => PhosphorThin.NumberOne,
            (Thin, Normal, Two) => PhosphorThin.NumberTwo,
            (Thin, Normal, Three) => PhosphorThin.NumberThree,
            (Thin, Normal, Four) => PhosphorThin.NumberFour,
            (Thin, Normal, Five) => PhosphorThin.NumberFive,
            (Thin, Normal, Six) => PhosphorThin.NumberSix,
            (Thin, Normal, Seven) => PhosphorThin.NumberSeven,
            (Thin, Normal, Eight) => PhosphorThin.NumberEight,
            (Thin, Normal, Nine) => PhosphorThin.NumberNine,
            (Thin, Circle, Zero) => PhosphorThin.NumberCircleZero,
            (Thin, Circle, One) => PhosphorThin.NumberCircleOne,
            (Thin, Circle, Two) => PhosphorThin.NumberCircleTwo,
            (Thin, Circle, Three) => PhosphorThin.NumberCircleThree,
            (Thin, Circle, Four) => PhosphorThin.NumberCircleFour,
            (Thin, Circle, Five) => PhosphorThin.NumberCircleFive,
            (Thin, Circle, Six) => PhosphorThin.NumberCircleSix,
            (Thin, Circle, Seven) => PhosphorThin.NumberCircleSeven,
            (Thin, Circle, Eight) => PhosphorThin.NumberCircleEight,
            (Thin, Circle, Nine) => PhosphorThin.NumberCircleNine,
            (Thin, Square, Zero) => PhosphorThin.NumberSquareZero,
            (Thin, Square, One) => PhosphorThin.NumberSquareOne,
            (Thin, Square, Two) => PhosphorThin.NumberSquareTwo,
            (Thin, Square, Three) => PhosphorThin.NumberSquareThree,
            (Thin, Square, Four) => PhosphorThin.NumberSquareFour,
            (Thin, Square, Five) => PhosphorThin.NumberSquareFive,
            (Thin, Square, Six) => PhosphorThin.NumberSquareSix,
            (Thin, Square, Seven) => PhosphorThin.NumberSquareSeven,
            (Thin, Square, Eight) => PhosphorThin.NumberSquareEight,
            (Thin, Square, Nine) => PhosphorThin.NumberSquareNine,
            // Light
            (Light, Normal, Zero) => PhosphorLight.NumberZero,
            (Light, Normal, One) => PhosphorLight.NumberOne,
            (Light, Normal, Two) => PhosphorLight.NumberTwo,
            (Light, Normal, Three) => PhosphorLight.NumberThree,
            (Light, Normal, Four) => PhosphorLight.NumberFour,
            (Light, Normal, Five) => PhosphorLight.NumberFive,
            (Light, Normal, Six) => PhosphorLight.NumberSix,
            (Light, Normal, Seven) => PhosphorLight.NumberSeven,
            (Light, Normal, Eight) => PhosphorLight.NumberEight,
            (Light, Normal, Nine) => PhosphorLight.NumberNine,
            (Light, Circle, Zero) => PhosphorLight.NumberCircleZero,
            (Light, Circle, One) => PhosphorLight.NumberCircleOne,
            (Light, Circle, Two) => PhosphorLight.NumberCircleTwo,
            (Light, Circle, Three) => PhosphorLight.NumberCircleThree,
            (Light, Circle, Four) => PhosphorLight.NumberCircleFour,
            (Light, Circle, Five) => PhosphorLight.NumberCircleFive,
            (Light, Circle, Six) => PhosphorLight.NumberCircleSix,
            (Light, Circle, Seven) => PhosphorLight.NumberCircleSeven,
            (Light, Circle, Eight) => PhosphorLight.NumberCircleEight,
            (Light, Circle, Nine) => PhosphorLight.NumberCircleNine,
            (Light, Square, Zero) => PhosphorLight.NumberSquareZero,
            (Light, Square, One) => PhosphorLight.NumberSquareOne,
            (Light, Square, Two) => PhosphorLight.NumberSquareTwo,
            (Light, Square, Three) => PhosphorLight.NumberSquareThree,
            (Light, Square, Four) => PhosphorLight.NumberSquareFour,
            (Light, Square, Five) => PhosphorLight.NumberSquareFive,
            (Light, Square, Six) => PhosphorLight.NumberSquareSix,
            (Light, Square, Seven) => PhosphorLight.NumberSquareSeven,
            (Light, Square, Eight) => PhosphorLight.NumberSquareEight,
            (Light, Square, Nine) => PhosphorLight.NumberSquareNine,
            // Bold
            (Bold, Normal, Zero) => PhosphorBold.NumberZero,
            (Bold, Normal, One) => PhosphorBold.NumberOne,
            (Bold, Normal, Two) => PhosphorBold.NumberTwo,
            (Bold, Normal, Three) => PhosphorBold.NumberThree,
            (Bold, Normal, Four) => PhosphorBold.NumberFour,
            (Bold, Normal, Five) => PhosphorBold.NumberFive,
            (Bold, Normal, Six) => PhosphorBold.NumberSix,
            (Bold, Normal, Seven) => PhosphorBold.NumberSeven,
            (Bold, Normal, Eight) => PhosphorBold.NumberEight,
            (Bold, Normal, Nine) => PhosphorBold.NumberNine,
            (Bold, Circle, Zero) => PhosphorBold.NumberCircleZero,
            (Bold, Circle, One) => PhosphorBold.NumberCircleOne,
            (Bold, Circle, Two) => PhosphorBold.NumberCircleTwo,
            (Bold, Circle, Three) => PhosphorBold.NumberCircleThree,
            (Bold, Circle, Four) => PhosphorBold.NumberCircleFour,
            (Bold, Circle, Five) => PhosphorBold.NumberCircleFive,
            (Bold, Circle, Six) => PhosphorBold.NumberCircleSix,
            (Bold, Circle, Seven) => PhosphorBold.NumberCircleSeven,
            (Bold, Circle, Eight) => PhosphorBold.NumberCircleEight,
            (Bold, Circle, Nine) => PhosphorBold.NumberCircleNine,
            (Bold, Square, Zero) => PhosphorBold.NumberSquareZero,
            (Bold, Square, One) => PhosphorBold.NumberSquareOne,
            (Bold, Square, Two) => PhosphorBold.NumberSquareTwo,
            (Bold, Square, Three) => PhosphorBold.NumberSquareThree,
            (Bold, Square, Four) => PhosphorBold.NumberSquareFour,
            (Bold, Square, Five) => PhosphorBold.NumberSquareFive,
            (Bold, Square, Six) => PhosphorBold.NumberSquareSix,
            (Bold, Square, Seven) => PhosphorBold.NumberSquareSeven,
            (Bold, Square, Eight) => PhosphorBold.NumberSquareEight,
            (Bold, Square, Nine) => PhosphorBold.NumberSquareNine,
            // Fill
            (Fill, Normal, Zero) => PhosphorFill.NumberZero,
            (Fill, Normal, One) => PhosphorFill.NumberOne,
            (Fill, Normal, Two) => PhosphorFill.NumberTwo,
            (Fill, Normal, Three) => PhosphorFill.NumberThree,
            (Fill, Normal, Four) => PhosphorFill.NumberFour,
            (Fill, Normal, Five) => PhosphorFill.NumberFive,
            (Fill, Normal, Six) => PhosphorFill.NumberSix,
            (Fill, Normal, Seven) => PhosphorFill.NumberSeven,
            (Fill, Normal, Eight) => PhosphorFill.NumberEight,
            (Fill, Normal, Nine) => PhosphorFill.NumberNine,
            (Fill, Circle, Zero) => PhosphorFill.NumberCircleZero,
            (Fill, Circle, One) => PhosphorFill.NumberCircleOne,
            (Fill, Circle, Two) => PhosphorFill.NumberCircleTwo,
            (Fill, Circle, Three) => PhosphorFill.NumberCircleThree,
            (Fill, Circle, Four) => PhosphorFill.NumberCircleFour,
            (Fill, Circle, Five) => PhosphorFill.NumberCircleFive,
            (Fill, Circle, Six) => PhosphorFill.NumberCircleSix,
            (Fill, Circle, Seven) => PhosphorFill.NumberCircleSeven,
            (Fill, Circle, Eight) => PhosphorFill.NumberCircleEight,
            (Fill, Circle, Nine) => PhosphorFill.NumberCircleNine,
            (Fill, Square, Zero) => PhosphorFill.NumberSquareZero,
            (Fill, Square, One) => PhosphorFill.NumberSquareOne,
            (Fill, Square, Two) => PhosphorFill.NumberSquareTwo,
            (Fill, Square, Three) => PhosphorFill.NumberSquareThree,
            (Fill, Square, Four) => PhosphorFill.NumberSquareFour,
            (Fill, Square, Five) => PhosphorFill.NumberSquareFive,
            (Fill, Square, Six) => PhosphorFill.NumberSquareSix,
            (Fill, Square, Seven) => PhosphorFill.NumberSquareSeven,
            (Fill, Square, Eight) => PhosphorFill.NumberSquareEight,
            (Fill, Square, Nine) => PhosphorFill.NumberSquareNine,
            // Duotone
            (Duotone, Normal, Zero) => PhosphorDuotone.NumberZero,
            (Duotone, Normal, One) => PhosphorDuotone.NumberOne,
            (Duotone, Normal, Two) => PhosphorDuotone.NumberTwo,
            (Duotone, Normal, Three) => PhosphorDuotone.NumberThree,
            (Duotone, Normal, Four) => PhosphorDuotone.NumberFour,
            (Duotone, Normal, Five) => PhosphorDuotone.NumberFive,
            (Duotone, Normal, Six) => PhosphorDuotone.NumberSix,
            (Duotone, Normal, Seven) => PhosphorDuotone.NumberSeven,
            (Duotone, Normal, Eight) => PhosphorDuotone.NumberEight,
            (Duotone, Normal, Nine) => PhosphorDuotone.NumberNine,
            (Duotone, Circle, Zero) => PhosphorDuotone.NumberCircleZero,
            (Duotone, Circle, One) => PhosphorDuotone.NumberCircleOne,
            (Duotone, Circle, Two) => PhosphorDuotone.NumberCircleTwo,
            (Duotone, Circle, Three) => PhosphorDuotone.NumberCircleThree,
            (Duotone, Circle, Four) => PhosphorDuotone.NumberCircleFour,
            (Duotone, Circle, Five) => PhosphorDuotone.NumberCircleFive,
            (Duotone, Circle, Six) => PhosphorDuotone.NumberCircleSix,
            (Duotone, Circle, Seven) => PhosphorDuotone.NumberCircleSeven,
            (Duotone, Circle, Eight) => PhosphorDuotone.NumberCircleEight,
            (Duotone, Circle, Nine) => PhosphorDuotone.NumberCircleNine,
            (Duotone, Square, Zero) => PhosphorDuotone.NumberSquareZero,
            (Duotone, Square, One) => PhosphorDuotone.NumberSquareOne,
            (Duotone, Square, Two) => PhosphorDuotone.NumberSquareTwo,
            (Duotone, Square, Three) => PhosphorDuotone.NumberSquareThree,
            (Duotone, Square, Four) => PhosphorDuotone.NumberSquareFour,
            (Duotone, Square, Five) => PhosphorDuotone.NumberSquareFive,
            (Duotone, Square, Six) => PhosphorDuotone.NumberSquareSix,
            (Duotone, Square, Seven) => PhosphorDuotone.NumberSquareSeven,
            (Duotone, Square, Eight) => PhosphorDuotone.NumberSquareEight,
            (Duotone, Square, Nine) => PhosphorDuotone.NumberSquareNine,
            _ => PhosphorRegular.NumberCircleZero
        };
    }
}

public enum NumberVariant
{
    Normal,
    Circle,
    Square
}

public enum NumberValue
{
    Zero,
    One,
    Two,
    Three,
    Four,
    Five,
    Six,
    Seven,
    Eight,
    Nine
}