using static MudBlazor.Phosphor.FileValue;

namespace MudBlazor.Phosphor;

public class SuperFileIcon : SuperIcon
{
    [Parameter]
    public FileValue Value { get; set; } = Normal;
    
    public override string GetIcon()
    {
        return (Weight, Value) switch
        {
            // Regular
            (Regular, Normal) => PhosphorRegular.File,
            (Regular, Dashed) => PhosphorRegular.FileDashed,
            (Regular, ArrowDown) => PhosphorRegular.FileArrowDown,
            (Regular, ArrowUp) => PhosphorRegular.FileArrowUp,
            (Regular, Minus) => PhosphorRegular.FileMinus,
            (Regular, Plus) => PhosphorRegular.FilePlus,
            (Regular, Archive) => PhosphorRegular.FileArchive,
            (Regular, Audio) => PhosphorRegular.FileAudio,
            (Regular, Video) => PhosphorRegular.FileVideo,
            (Regular, Image) => PhosphorRegular.FileImage,
            (Regular, Text) => PhosphorRegular.FileText,
            (Regular, Code) => PhosphorRegular.FileCode,
            (Regular, Cloud) => PhosphorRegular.FileCloud,
            (Regular, Lock) => PhosphorRegular.FileLock,
            (Regular, MagnifyingGlass) => PhosphorRegular.FileMagnifyingGlass,
            (Regular, X) => PhosphorRegular.FileX,
            (Regular, C) => PhosphorRegular.FileC,
            (Regular, CSharp) => PhosphorRegular.FileCSharp,
            (Regular, Cpp) => PhosphorRegular.FileCpp,
            (Regular, Css) => PhosphorRegular.FileCss,
            (Regular, Csv) => PhosphorRegular.FileCsv,
            (Regular, Doc) => PhosphorRegular.FileDoc,
            (Regular, Html) => PhosphorRegular.FileHtml,
            (Regular, Ini) => PhosphorRegular.FileIni,
            (Regular, Jpg) => PhosphorRegular.FileJpg,
            (Regular, Js) => PhosphorRegular.FileJs,
            (Regular, Jsx) => PhosphorRegular.FileJsx,
            (Regular, Md) => PhosphorRegular.FileMd,
            (Regular, Pdf) => PhosphorRegular.FilePdf,
            (Regular, Png) => PhosphorRegular.FilePng,
            (Regular, Ppt) => PhosphorRegular.FilePpt,
            (Regular, Py) => PhosphorRegular.FilePy,
            (Regular, Rs) => PhosphorRegular.FileRs,
            (Regular, Sql) => PhosphorRegular.FileSql,
            (Regular, Svg) => PhosphorRegular.FileSvg,
            (Regular, Ts) => PhosphorRegular.FileTs,
            (Regular, Tsx) => PhosphorRegular.FileTsx,
            (Regular, Txt) => PhosphorRegular.FileTxt,
            (Regular, Vue) => PhosphorRegular.FileVue,
            (Regular, Xls) => PhosphorRegular.FileXls,
            (Regular, Zip) => PhosphorRegular.FileZip,
            // Thin
            (Thin, Normal) => PhosphorThin.File,
            (Thin, Dashed) => PhosphorThin.FileDashed,
            (Thin, ArrowDown) => PhosphorThin.FileArrowDown,
            (Thin, ArrowUp) => PhosphorThin.FileArrowUp,
            (Thin, Minus) => PhosphorThin.FileMinus,
            (Thin, Plus) => PhosphorThin.FilePlus,
            (Thin, Archive) => PhosphorThin.FileArchive,
            (Thin, Audio) => PhosphorThin.FileAudio,
            (Thin, Video) => PhosphorThin.FileVideo,
            (Thin, Image) => PhosphorThin.FileImage,
            (Thin, Text) => PhosphorThin.FileText,
            (Thin, Code) => PhosphorThin.FileCode,
            (Thin, Cloud) => PhosphorThin.FileCloud,
            (Thin, Lock) => PhosphorThin.FileLock,
            (Thin, MagnifyingGlass) => PhosphorThin.FileMagnifyingGlass,
            (Thin, X) => PhosphorThin.FileX,
            (Thin, C) => PhosphorThin.FileC,
            (Thin, CSharp) => PhosphorThin.FileCSharp,
            (Thin, Cpp) => PhosphorThin.FileCpp,
            (Thin, Css) => PhosphorThin.FileCss,
            (Thin, Csv) => PhosphorThin.FileCsv,
            (Thin, Doc) => PhosphorThin.FileDoc,
            (Thin, Html) => PhosphorThin.FileHtml,
            (Thin, Ini) => PhosphorThin.FileIni,
            (Thin, Jpg) => PhosphorThin.FileJpg,
            (Thin, Js) => PhosphorThin.FileJs,
            (Thin, Jsx) => PhosphorThin.FileJsx,
            (Thin, Md) => PhosphorThin.FileMd,
            (Thin, Pdf) => PhosphorThin.FilePdf,
            (Thin, Png) => PhosphorThin.FilePng,
            (Thin, Ppt) => PhosphorThin.FilePpt,
            (Thin, Py) => PhosphorThin.FilePy,
            (Thin, Rs) => PhosphorThin.FileRs,
            (Thin, Sql) => PhosphorThin.FileSql,
            (Thin, Svg) => PhosphorThin.FileSvg,
            (Thin, Ts) => PhosphorThin.FileTs,
            (Thin, Tsx) => PhosphorThin.FileTsx,
            (Thin, Txt) => PhosphorThin.FileTxt,
            (Thin, Vue) => PhosphorThin.FileVue,
            (Thin, Xls) => PhosphorThin.FileXls,
            (Thin, Zip) => PhosphorThin.FileZip,
            // Light
            (Light, Normal) => PhosphorLight.File,
            (Light, Dashed) => PhosphorLight.FileDashed,
            (Light, ArrowDown) => PhosphorLight.FileArrowDown,
            (Light, ArrowUp) => PhosphorLight.FileArrowUp,
            (Light, Minus) => PhosphorLight.FileMinus,
            (Light, Plus) => PhosphorLight.FilePlus,
            (Light, Archive) => PhosphorLight.FileArchive,
            (Light, Audio) => PhosphorLight.FileAudio,
            (Light, Video) => PhosphorLight.FileVideo,
            (Light, Image) => PhosphorLight.FileImage,
            (Light, Text) => PhosphorLight.FileText,
            (Light, Code) => PhosphorLight.FileCode,
            (Light, Cloud) => PhosphorLight.FileCloud,
            (Light, Lock) => PhosphorLight.FileLock,
            (Light, MagnifyingGlass) => PhosphorLight.FileMagnifyingGlass,
            (Light, X) => PhosphorLight.FileX,
            (Light, C) => PhosphorLight.FileC,
            (Light, CSharp) => PhosphorLight.FileCSharp,
            (Light, Cpp) => PhosphorLight.FileCpp,
            (Light, Css) => PhosphorLight.FileCss,
            (Light, Csv) => PhosphorLight.FileCsv,
            (Light, Doc) => PhosphorLight.FileDoc,
            (Light, Html) => PhosphorLight.FileHtml,
            (Light, Ini) => PhosphorLight.FileIni,
            (Light, Jpg) => PhosphorLight.FileJpg,
            (Light, Js) => PhosphorLight.FileJs,
            (Light, Jsx) => PhosphorLight.FileJsx,
            (Light, Md) => PhosphorLight.FileMd,
            (Light, Pdf) => PhosphorLight.FilePdf,
            (Light, Png) => PhosphorLight.FilePng,
            (Light, Ppt) => PhosphorLight.FilePpt,
            (Light, Py) => PhosphorLight.FilePy,
            (Light, Rs) => PhosphorLight.FileRs,
            (Light, Sql) => PhosphorLight.FileSql,
            (Light, Svg) => PhosphorLight.FileSvg,
            (Light, Ts) => PhosphorLight.FileTs,
            (Light, Tsx) => PhosphorLight.FileTsx,
            (Light, Txt) => PhosphorLight.FileTxt,
            (Light, Vue) => PhosphorLight.FileVue,
            (Light, Xls) => PhosphorLight.FileXls,
            (Light, Zip) => PhosphorLight.FileZip,
            // Bold
            (Bold, Normal) => PhosphorBold.File,
            (Bold, Dashed) => PhosphorBold.FileDashed,
            (Bold, ArrowDown) => PhosphorBold.FileArrowDown,
            (Bold, ArrowUp) => PhosphorBold.FileArrowUp,
            (Bold, Minus) => PhosphorBold.FileMinus,
            (Bold, Plus) => PhosphorBold.FilePlus,
            (Bold, Archive) => PhosphorBold.FileArchive,
            (Bold, Audio) => PhosphorBold.FileAudio,
            (Bold, Video) => PhosphorBold.FileVideo,
            (Bold, Image) => PhosphorBold.FileImage,
            (Bold, Text) => PhosphorBold.FileText,
            (Bold, Code) => PhosphorBold.FileCode,
            (Bold, Cloud) => PhosphorBold.FileCloud,
            (Bold, Lock) => PhosphorBold.FileLock,
            (Bold, MagnifyingGlass) => PhosphorBold.FileMagnifyingGlass,
            (Bold, X) => PhosphorBold.FileX,
            (Bold, C) => PhosphorBold.FileC,
            (Bold, CSharp) => PhosphorBold.FileCSharp,
            (Bold, Cpp) => PhosphorBold.FileCpp,
            (Bold, Css) => PhosphorBold.FileCss,
            (Bold, Csv) => PhosphorBold.FileCsv,
            (Bold, Doc) => PhosphorBold.FileDoc,
            (Bold, Html) => PhosphorBold.FileHtml,
            (Bold, Ini) => PhosphorBold.FileIni,
            (Bold, Jpg) => PhosphorBold.FileJpg,
            (Bold, Js) => PhosphorBold.FileJs,
            (Bold, Jsx) => PhosphorBold.FileJsx,
            (Bold, Md) => PhosphorBold.FileMd,
            (Bold, Pdf) => PhosphorBold.FilePdf,
            (Bold, Png) => PhosphorBold.FilePng,
            (Bold, Ppt) => PhosphorBold.FilePpt,
            (Bold, Py) => PhosphorBold.FilePy,
            (Bold, Rs) => PhosphorBold.FileRs,
            (Bold, Sql) => PhosphorBold.FileSql,
            (Bold, Svg) => PhosphorBold.FileSvg,
            (Bold, Ts) => PhosphorBold.FileTs,
            (Bold, Tsx) => PhosphorBold.FileTsx,
            (Bold, Txt) => PhosphorBold.FileTxt,
            (Bold, Vue) => PhosphorBold.FileVue,
            (Bold, Xls) => PhosphorBold.FileXls,
            (Bold, Zip) => PhosphorBold.FileZip,
            // Fill
            (Fill, Normal) => PhosphorFill.File,
            (Fill, Dashed) => PhosphorFill.FileDashed,
            (Fill, ArrowDown) => PhosphorFill.FileArrowDown,
            (Fill, ArrowUp) => PhosphorFill.FileArrowUp,
            (Fill, Minus) => PhosphorFill.FileMinus,
            (Fill, Plus) => PhosphorFill.FilePlus,
            (Fill, Archive) => PhosphorFill.FileArchive,
            (Fill, Audio) => PhosphorFill.FileAudio,
            (Fill, Video) => PhosphorFill.FileVideo,
            (Fill, Image) => PhosphorFill.FileImage,
            (Fill, Text) => PhosphorFill.FileText,
            (Fill, Code) => PhosphorFill.FileCode,
            (Fill, Cloud) => PhosphorFill.FileCloud,
            (Fill, Lock) => PhosphorFill.FileLock,
            (Fill, MagnifyingGlass) => PhosphorFill.FileMagnifyingGlass,
            (Fill, X) => PhosphorFill.FileX,
            (Fill, C) => PhosphorFill.FileC,
            (Fill, CSharp) => PhosphorFill.FileCSharp,
            (Fill, Cpp) => PhosphorFill.FileCpp,
            (Fill, Css) => PhosphorFill.FileCss,
            (Fill, Csv) => PhosphorFill.FileCsv,
            (Fill, Doc) => PhosphorFill.FileDoc,
            (Fill, Html) => PhosphorFill.FileHtml,
            (Fill, Ini) => PhosphorFill.FileIni,
            (Fill, Jpg) => PhosphorFill.FileJpg,
            (Fill, Js) => PhosphorFill.FileJs,
            (Fill, Jsx) => PhosphorFill.FileJsx,
            (Fill, Md) => PhosphorFill.FileMd,
            (Fill, Pdf) => PhosphorFill.FilePdf,
            (Fill, Png) => PhosphorFill.FilePng,
            (Fill, Ppt) => PhosphorFill.FilePpt,
            (Fill, Py) => PhosphorFill.FilePy,
            (Fill, Rs) => PhosphorFill.FileRs,
            (Fill, Sql) => PhosphorFill.FileSql,
            (Fill, Svg) => PhosphorFill.FileSvg,
            (Fill, Ts) => PhosphorFill.FileTs,
            (Fill, Tsx) => PhosphorFill.FileTsx,
            (Fill, Txt) => PhosphorFill.FileTxt,
            (Fill, Vue) => PhosphorFill.FileVue,
            (Fill, Xls) => PhosphorFill.FileXls,
            (Fill, Zip) => PhosphorFill.FileZip,
            // Duotone
            (Duotone, Normal) => PhosphorDuotone.File,
            (Duotone, Dashed) => PhosphorDuotone.FileDashed,
            (Duotone, ArrowDown) => PhosphorDuotone.FileArrowDown,
            (Duotone, ArrowUp) => PhosphorDuotone.FileArrowUp,
            (Duotone, Minus) => PhosphorDuotone.FileMinus,
            (Duotone, Plus) => PhosphorDuotone.FilePlus,
            (Duotone, Archive) => PhosphorDuotone.FileArchive,
            (Duotone, Audio) => PhosphorDuotone.FileAudio,
            (Duotone, Video) => PhosphorDuotone.FileVideo,
            (Duotone, Image) => PhosphorDuotone.FileImage,
            (Duotone, Text) => PhosphorDuotone.FileText,
            (Duotone, Code) => PhosphorDuotone.FileCode,
            (Duotone, Cloud) => PhosphorDuotone.FileCloud,
            (Duotone, Lock) => PhosphorDuotone.FileLock,
            (Duotone, MagnifyingGlass) => PhosphorDuotone.FileMagnifyingGlass,
            (Duotone, X) => PhosphorDuotone.FileX,
            (Duotone, C) => PhosphorDuotone.FileC,
            (Duotone, CSharp) => PhosphorDuotone.FileCSharp,
            (Duotone, Cpp) => PhosphorDuotone.FileCpp,
            (Duotone, Css) => PhosphorDuotone.FileCss,
            (Duotone, Csv) => PhosphorDuotone.FileCsv,
            (Duotone, Doc) => PhosphorDuotone.FileDoc,
            (Duotone, Html) => PhosphorDuotone.FileHtml,
            (Duotone, Ini) => PhosphorDuotone.FileIni,
            (Duotone, Jpg) => PhosphorDuotone.FileJpg,
            (Duotone, Js) => PhosphorDuotone.FileJs,
            (Duotone, Jsx) => PhosphorDuotone.FileJsx,
            (Duotone, Md) => PhosphorDuotone.FileMd,
            (Duotone, Pdf) => PhosphorDuotone.FilePdf,
            (Duotone, Png) => PhosphorDuotone.FilePng,
            (Duotone, Ppt) => PhosphorDuotone.FilePpt,
            (Duotone, Py) => PhosphorDuotone.FilePy,
            (Duotone, Rs) => PhosphorDuotone.FileRs,
            (Duotone, Sql) => PhosphorDuotone.FileSql,
            (Duotone, Svg) => PhosphorDuotone.FileSvg,
            (Duotone, Ts) => PhosphorDuotone.FileTs,
            (Duotone, Tsx) => PhosphorDuotone.FileTsx,
            (Duotone, Txt) => PhosphorDuotone.FileTxt,
            (Duotone, Vue) => PhosphorDuotone.FileVue,
            (Duotone, Xls) => PhosphorDuotone.FileXls,
            (Duotone, Zip) => PhosphorDuotone.FileZip,
        };
    }
}

public enum FileValue
{
    Normal,
    Dashed,
    ArrowDown,
    ArrowUp,
    Minus,
    Plus,
    Archive,
    
    Audio,
    Video,
    Image,
    Text,
    Code,
    Cloud,
    Lock,
    MagnifyingGlass,
    X,

    C,
    CSharp,
    Cpp,
    Css,
    Csv,
    Doc,
    Html,
    Ini,
    Jpg,
    Js,
    Jsx,
    Md,
    Pdf,
    Png,
    Ppt,
    Py,
    Rs,
    Sql,
    Svg,
    Ts,
    Tsx,
    Txt,
    Vue,
    Xls,
    Zip,
}