using Microsoft.AspNetCore.Components;
using MudBlazor;
using Phosphor.Models;
using static Phosphor.Components.SuperIcons.NumberValue;
using static Phosphor.Components.SuperIcons.NumberVariant;
using static Phosphor.Models.IconWeight;

namespace Phosphor.Components.SuperIcons;

public class SuperNumberIcon : SuperIcon
{
    [Parameter]
    public NumberVariant Variant { get; set; } = Normal;
    
    [Parameter]
    public NumberValue Value { get; set; } = Zero;
    
    public override string GetIcon()
    {
        return (Weight, Variant, Value) switch
        {
            // Regular
            (Regular, Normal, Zero) => Icons.Phosphor.Regular.NumberZero,
            (Regular, Normal, One) => Icons.Phosphor.Regular.NumberOne,
            (Regular, Normal, Two) => Icons.Phosphor.Regular.NumberTwo,
            (Regular, Normal, Three) => Icons.Phosphor.Regular.NumberThree,
            (Regular, Normal, Four) => Icons.Phosphor.Regular.NumberFour,
            (Regular, Normal, Five) => Icons.Phosphor.Regular.NumberFive,
            (Regular, Normal, Six) => Icons.Phosphor.Regular.NumberSix,
            (Regular, Normal, Seven) => Icons.Phosphor.Regular.NumberSeven,
            (Regular, Normal, Eight) => Icons.Phosphor.Regular.NumberEight,
            (Regular, Normal, Nine) => Icons.Phosphor.Regular.NumberNine,
            (Regular, Circle, Zero) => Icons.Phosphor.Regular.NumberCircleZero,
            (Regular, Circle, One) => Icons.Phosphor.Regular.NumberCircleOne,
            (Regular, Circle, Two) => Icons.Phosphor.Regular.NumberCircleTwo,
            (Regular, Circle, Three) => Icons.Phosphor.Regular.NumberCircleThree,
            (Regular, Circle, Four) => Icons.Phosphor.Regular.NumberCircleFour,
            (Regular, Circle, Five) => Icons.Phosphor.Regular.NumberCircleFive,
            (Regular, Circle, Six) => Icons.Phosphor.Regular.NumberCircleSix,
            (Regular, Circle, Seven) => Icons.Phosphor.Regular.NumberCircleSeven,
            (Regular, Circle, Eight) => Icons.Phosphor.Regular.NumberCircleEight,
            (Regular, Circle, Nine) => Icons.Phosphor.Regular.NumberCircleNine,
            (Regular, Square, Zero) => Icons.Phosphor.Regular.NumberSquareZero,
            (Regular, Square, One) => Icons.Phosphor.Regular.NumberSquareOne,
            (Regular, Square, Two) => Icons.Phosphor.Regular.NumberSquareTwo,
            (Regular, Square, Three) => Icons.Phosphor.Regular.NumberSquareThree,
            (Regular, Square, Four) => Icons.Phosphor.Regular.NumberSquareFour,
            (Regular, Square, Five) => Icons.Phosphor.Regular.NumberSquareFive,
            (Regular, Square, Six) => Icons.Phosphor.Regular.NumberSquareSix,
            (Regular, Square, Seven) => Icons.Phosphor.Regular.NumberSquareSeven,
            (Regular, Square, Eight) => Icons.Phosphor.Regular.NumberSquareEight,
            (Regular, Square, Nine) => Icons.Phosphor.Regular.NumberSquareNine,
            // Thin
            (Thin, Normal, Zero) => Icons.Phosphor.Thin.NumberZero,
            (Thin, Normal, One) => Icons.Phosphor.Thin.NumberOne,
            (Thin, Normal, Two) => Icons.Phosphor.Thin.NumberTwo,
            (Thin, Normal, Three) => Icons.Phosphor.Thin.NumberThree,
            (Thin, Normal, Four) => Icons.Phosphor.Thin.NumberFour,
            (Thin, Normal, Five) => Icons.Phosphor.Thin.NumberFive,
            (Thin, Normal, Six) => Icons.Phosphor.Thin.NumberSix,
            (Thin, Normal, Seven) => Icons.Phosphor.Thin.NumberSeven,
            (Thin, Normal, Eight) => Icons.Phosphor.Thin.NumberEight,
            (Thin, Normal, Nine) => Icons.Phosphor.Thin.NumberNine,
            (Thin, Circle, Zero) => Icons.Phosphor.Thin.NumberCircleZero,
            (Thin, Circle, One) => Icons.Phosphor.Thin.NumberCircleOne,
            (Thin, Circle, Two) => Icons.Phosphor.Thin.NumberCircleTwo,
            (Thin, Circle, Three) => Icons.Phosphor.Thin.NumberCircleThree,
            (Thin, Circle, Four) => Icons.Phosphor.Thin.NumberCircleFour,
            (Thin, Circle, Five) => Icons.Phosphor.Thin.NumberCircleFive,
            (Thin, Circle, Six) => Icons.Phosphor.Thin.NumberCircleSix,
            (Thin, Circle, Seven) => Icons.Phosphor.Thin.NumberCircleSeven,
            (Thin, Circle, Eight) => Icons.Phosphor.Thin.NumberCircleEight,
            (Thin, Circle, Nine) => Icons.Phosphor.Thin.NumberCircleNine,
            (Thin, Square, Zero) => Icons.Phosphor.Thin.NumberSquareZero,
            (Thin, Square, One) => Icons.Phosphor.Thin.NumberSquareOne,
            (Thin, Square, Two) => Icons.Phosphor.Thin.NumberSquareTwo,
            (Thin, Square, Three) => Icons.Phosphor.Thin.NumberSquareThree,
            (Thin, Square, Four) => Icons.Phosphor.Thin.NumberSquareFour,
            (Thin, Square, Five) => Icons.Phosphor.Thin.NumberSquareFive,
            (Thin, Square, Six) => Icons.Phosphor.Thin.NumberSquareSix,
            (Thin, Square, Seven) => Icons.Phosphor.Thin.NumberSquareSeven,
            (Thin, Square, Eight) => Icons.Phosphor.Thin.NumberSquareEight,
            (Thin, Square, Nine) => Icons.Phosphor.Thin.NumberSquareNine,
            // Light
            (Light, Normal, Zero) => Icons.Phosphor.Light.NumberZero,
            (Light, Normal, One) => Icons.Phosphor.Light.NumberOne,
            (Light, Normal, Two) => Icons.Phosphor.Light.NumberTwo,
            (Light, Normal, Three) => Icons.Phosphor.Light.NumberThree,
            (Light, Normal, Four) => Icons.Phosphor.Light.NumberFour,
            (Light, Normal, Five) => Icons.Phosphor.Light.NumberFive,
            (Light, Normal, Six) => Icons.Phosphor.Light.NumberSix,
            (Light, Normal, Seven) => Icons.Phosphor.Light.NumberSeven,
            (Light, Normal, Eight) => Icons.Phosphor.Light.NumberEight,
            (Light, Normal, Nine) => Icons.Phosphor.Light.NumberNine,
            (Light, Circle, Zero) => Icons.Phosphor.Light.NumberCircleZero,
            (Light, Circle, One) => Icons.Phosphor.Light.NumberCircleOne,
            (Light, Circle, Two) => Icons.Phosphor.Light.NumberCircleTwo,
            (Light, Circle, Three) => Icons.Phosphor.Light.NumberCircleThree,
            (Light, Circle, Four) => Icons.Phosphor.Light.NumberCircleFour,
            (Light, Circle, Five) => Icons.Phosphor.Light.NumberCircleFive,
            (Light, Circle, Six) => Icons.Phosphor.Light.NumberCircleSix,
            (Light, Circle, Seven) => Icons.Phosphor.Light.NumberCircleSeven,
            (Light, Circle, Eight) => Icons.Phosphor.Light.NumberCircleEight,
            (Light, Circle, Nine) => Icons.Phosphor.Light.NumberCircleNine,
            (Light, Square, Zero) => Icons.Phosphor.Light.NumberSquareZero,
            (Light, Square, One) => Icons.Phosphor.Light.NumberSquareOne,
            (Light, Square, Two) => Icons.Phosphor.Light.NumberSquareTwo,
            (Light, Square, Three) => Icons.Phosphor.Light.NumberSquareThree,
            (Light, Square, Four) => Icons.Phosphor.Light.NumberSquareFour,
            (Light, Square, Five) => Icons.Phosphor.Light.NumberSquareFive,
            (Light, Square, Six) => Icons.Phosphor.Light.NumberSquareSix,
            (Light, Square, Seven) => Icons.Phosphor.Light.NumberSquareSeven,
            (Light, Square, Eight) => Icons.Phosphor.Light.NumberSquareEight,
            (Light, Square, Nine) => Icons.Phosphor.Light.NumberSquareNine,
            // Bold
            (Bold, Normal, Zero) => Icons.Phosphor.Bold.NumberZero,
            (Bold, Normal, One) => Icons.Phosphor.Bold.NumberOne,
            (Bold, Normal, Two) => Icons.Phosphor.Bold.NumberTwo,
            (Bold, Normal, Three) => Icons.Phosphor.Bold.NumberThree,
            (Bold, Normal, Four) => Icons.Phosphor.Bold.NumberFour,
            (Bold, Normal, Five) => Icons.Phosphor.Bold.NumberFive,
            (Bold, Normal, Six) => Icons.Phosphor.Bold.NumberSix,
            (Bold, Normal, Seven) => Icons.Phosphor.Bold.NumberSeven,
            (Bold, Normal, Eight) => Icons.Phosphor.Bold.NumberEight,
            (Bold, Normal, Nine) => Icons.Phosphor.Bold.NumberNine,
            (Bold, Circle, Zero) => Icons.Phosphor.Bold.NumberCircleZero,
            (Bold, Circle, One) => Icons.Phosphor.Bold.NumberCircleOne,
            (Bold, Circle, Two) => Icons.Phosphor.Bold.NumberCircleTwo,
            (Bold, Circle, Three) => Icons.Phosphor.Bold.NumberCircleThree,
            (Bold, Circle, Four) => Icons.Phosphor.Bold.NumberCircleFour,
            (Bold, Circle, Five) => Icons.Phosphor.Bold.NumberCircleFive,
            (Bold, Circle, Six) => Icons.Phosphor.Bold.NumberCircleSix,
            (Bold, Circle, Seven) => Icons.Phosphor.Bold.NumberCircleSeven,
            (Bold, Circle, Eight) => Icons.Phosphor.Bold.NumberCircleEight,
            (Bold, Circle, Nine) => Icons.Phosphor.Bold.NumberCircleNine,
            (Bold, Square, Zero) => Icons.Phosphor.Bold.NumberSquareZero,
            (Bold, Square, One) => Icons.Phosphor.Bold.NumberSquareOne,
            (Bold, Square, Two) => Icons.Phosphor.Bold.NumberSquareTwo,
            (Bold, Square, Three) => Icons.Phosphor.Bold.NumberSquareThree,
            (Bold, Square, Four) => Icons.Phosphor.Bold.NumberSquareFour,
            (Bold, Square, Five) => Icons.Phosphor.Bold.NumberSquareFive,
            (Bold, Square, Six) => Icons.Phosphor.Bold.NumberSquareSix,
            (Bold, Square, Seven) => Icons.Phosphor.Bold.NumberSquareSeven,
            (Bold, Square, Eight) => Icons.Phosphor.Bold.NumberSquareEight,
            (Bold, Square, Nine) => Icons.Phosphor.Bold.NumberSquareNine,
            // Fill
            (Fill, Normal, Zero) => Icons.Phosphor.Fill.NumberZero,
            (Fill, Normal, One) => Icons.Phosphor.Fill.NumberOne,
            (Fill, Normal, Two) => Icons.Phosphor.Fill.NumberTwo,
            (Fill, Normal, Three) => Icons.Phosphor.Fill.NumberThree,
            (Fill, Normal, Four) => Icons.Phosphor.Fill.NumberFour,
            (Fill, Normal, Five) => Icons.Phosphor.Fill.NumberFive,
            (Fill, Normal, Six) => Icons.Phosphor.Fill.NumberSix,
            (Fill, Normal, Seven) => Icons.Phosphor.Fill.NumberSeven,
            (Fill, Normal, Eight) => Icons.Phosphor.Fill.NumberEight,
            (Fill, Normal, Nine) => Icons.Phosphor.Fill.NumberNine,
            (Fill, Circle, Zero) => Icons.Phosphor.Fill.NumberCircleZero,
            (Fill, Circle, One) => Icons.Phosphor.Fill.NumberCircleOne,
            (Fill, Circle, Two) => Icons.Phosphor.Fill.NumberCircleTwo,
            (Fill, Circle, Three) => Icons.Phosphor.Fill.NumberCircleThree,
            (Fill, Circle, Four) => Icons.Phosphor.Fill.NumberCircleFour,
            (Fill, Circle, Five) => Icons.Phosphor.Fill.NumberCircleFive,
            (Fill, Circle, Six) => Icons.Phosphor.Fill.NumberCircleSix,
            (Fill, Circle, Seven) => Icons.Phosphor.Fill.NumberCircleSeven,
            (Fill, Circle, Eight) => Icons.Phosphor.Fill.NumberCircleEight,
            (Fill, Circle, Nine) => Icons.Phosphor.Fill.NumberCircleNine,
            (Fill, Square, Zero) => Icons.Phosphor.Fill.NumberSquareZero,
            (Fill, Square, One) => Icons.Phosphor.Fill.NumberSquareOne,
            (Fill, Square, Two) => Icons.Phosphor.Fill.NumberSquareTwo,
            (Fill, Square, Three) => Icons.Phosphor.Fill.NumberSquareThree,
            (Fill, Square, Four) => Icons.Phosphor.Fill.NumberSquareFour,
            (Fill, Square, Five) => Icons.Phosphor.Fill.NumberSquareFive,
            (Fill, Square, Six) => Icons.Phosphor.Fill.NumberSquareSix,
            (Fill, Square, Seven) => Icons.Phosphor.Fill.NumberSquareSeven,
            (Fill, Square, Eight) => Icons.Phosphor.Fill.NumberSquareEight,
            (Fill, Square, Nine) => Icons.Phosphor.Fill.NumberSquareNine,
            // Duotone
            (Duotone, Normal, Zero) => Icons.Phosphor.Duotone.NumberZero,
            (Duotone, Normal, One) => Icons.Phosphor.Duotone.NumberOne,
            (Duotone, Normal, Two) => Icons.Phosphor.Duotone.NumberTwo,
            (Duotone, Normal, Three) => Icons.Phosphor.Duotone.NumberThree,
            (Duotone, Normal, Four) => Icons.Phosphor.Duotone.NumberFour,
            (Duotone, Normal, Five) => Icons.Phosphor.Duotone.NumberFive,
            (Duotone, Normal, Six) => Icons.Phosphor.Duotone.NumberSix,
            (Duotone, Normal, Seven) => Icons.Phosphor.Duotone.NumberSeven,
            (Duotone, Normal, Eight) => Icons.Phosphor.Duotone.NumberEight,
            (Duotone, Normal, Nine) => Icons.Phosphor.Duotone.NumberNine,
            (Duotone, Circle, Zero) => Icons.Phosphor.Duotone.NumberCircleZero,
            (Duotone, Circle, One) => Icons.Phosphor.Duotone.NumberCircleOne,
            (Duotone, Circle, Two) => Icons.Phosphor.Duotone.NumberCircleTwo,
            (Duotone, Circle, Three) => Icons.Phosphor.Duotone.NumberCircleThree,
            (Duotone, Circle, Four) => Icons.Phosphor.Duotone.NumberCircleFour,
            (Duotone, Circle, Five) => Icons.Phosphor.Duotone.NumberCircleFive,
            (Duotone, Circle, Six) => Icons.Phosphor.Duotone.NumberCircleSix,
            (Duotone, Circle, Seven) => Icons.Phosphor.Duotone.NumberCircleSeven,
            (Duotone, Circle, Eight) => Icons.Phosphor.Duotone.NumberCircleEight,
            (Duotone, Circle, Nine) => Icons.Phosphor.Duotone.NumberCircleNine,
            (Duotone, Square, Zero) => Icons.Phosphor.Duotone.NumberSquareZero,
            (Duotone, Square, One) => Icons.Phosphor.Duotone.NumberSquareOne,
            (Duotone, Square, Two) => Icons.Phosphor.Duotone.NumberSquareTwo,
            (Duotone, Square, Three) => Icons.Phosphor.Duotone.NumberSquareThree,
            (Duotone, Square, Four) => Icons.Phosphor.Duotone.NumberSquareFour,
            (Duotone, Square, Five) => Icons.Phosphor.Duotone.NumberSquareFive,
            (Duotone, Square, Six) => Icons.Phosphor.Duotone.NumberSquareSix,
            (Duotone, Square, Seven) => Icons.Phosphor.Duotone.NumberSquareSeven,
            (Duotone, Square, Eight) => Icons.Phosphor.Duotone.NumberSquareEight,
            (Duotone, Square, Nine) => Icons.Phosphor.Duotone.NumberSquareNine,
            _ => Icons.Phosphor.Regular.NumberCircleZero
        };
    }
}

public enum NumberVariant
{
    Normal,
    Circle,
    Square
}

public enum NumberValue
{
    Zero,
    One,
    Two,
    Three,
    Four,
    Five,
    Six,
    Seven,
    Eight,
    Nine
}