<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>MudBlazor.Phosphor</RootNamespace>
  </PropertyGroup>


  <ItemGroup>
    <SupportedPlatform Include="browser"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.0" />
    <PackageReference Include="MudBlazor" Version="8.15.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\output\Icons.cs">
      <Link>Icons.cs</Link>
    </Compile>
    <Compile Include="..\output\Icons.Phosphor.Bold.cs">
      <Link>Icons.Phosphor.Bold.cs</Link>
    </Compile>
    <Compile Include="..\output\Icons.Phosphor.Duotone.cs">
      <Link>Icons.Phosphor.Duotone.cs</Link>
    </Compile>
    <Compile Include="..\output\Icons.Phosphor.Fill.cs">
      <Link>Icons.Phosphor.Fill.cs</Link>
    </Compile>
    <Compile Include="..\output\Icons.Phosphor.Light.cs">
      <Link>Icons.Phosphor.Light.cs</Link>
    </Compile>
    <Compile Include="..\output\Icons.Phosphor.Regular.cs">
      <Link>Icons.Phosphor.Regular.cs</Link>
    </Compile>
    <Compile Include="..\output\Icons.Phosphor.Thin.cs">
      <Link>Icons.Phosphor.Thin.cs</Link>
    </Compile>
  </ItemGroup>

</Project>
